platform :ios, '7.0'
inhibit_all_warnings!
use_frameworks!

target 'KSYRTCStreamerDemo' do
   pod 'KSYRTCLive',:path => '../'
   pod 'libksygpulive/KSYGPUResource'
   pod 'libksygpulive/libksygpulive'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    puts "!!!! #{target.name}"
  end
end
